---
# ============================================================
# Banner
# Template : CX_banner.j2
# Variables: banner.motd, banner.exec
# ============================================================

banner:
  motd: ""
  exec: ""
