---
# ============================================================
# VLANs
# Template : CX_vlans.j2
# Variables: vlans[].id, .name
# ============================================================
 
vlans: []
# - id: 100
#   name: SERVERS