---
# ============================================================
# VSF
# Template : CX_vsf.j2
# Variables: vsf.enabled, vsf.members[].id,
#            vsf.members[].link1, vsf.members[].link2
# ============================================================
vsf:
  enabled: false
  members: []
  # - id: 1
  #   link1: "1/1/49"
  #   link2: "1/1/50"
  # - id: 2
  #   link1: "1/1/25"
  #   link2: "1/1/26"
