interface_groups: []
physical_interfaces:
  - name: "1/1/1"
    description: "User access"
    admin: up
    mtu: 1500
    routed: false
    port_type: access
    access_vlan: "10"
    trunk_allowed_vlans: ""
    trunk_native_vlan: 1
  - name: "2/1/1"
    description: "Member 2 user port"
    admin: up
    mtu: 1500
    routed: false
    port_type: access
    access_vlan: "10"
    trunk_allowed_vlans: ""
    trunk_native_vlan: 1
lag_interfaces: []
loopback_interfaces: []
vlan_interfaces: []
